import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='sticky top-0 flex h-[10vh] w-[100vw] items-center justify-around bg-blue-100'>
          <Link className='rounded-lg bg-slate-400 p-5' href={'/'}>
            All Characters
          </Link>
          <Link className='rounded-lg bg-slate-400 p-5' href={'/favorites'}>
            Favorites
          </Link>
        </header>
        {children}
      </body>
    </html>
  )
}
