import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 w-[100vw] h-[10vh] bg-blue-100 flex items-center justify-around">
          <Link className="bg-slate-400 p-5 rounded-lg" href={"/"}>
            All Characters
          </Link>
          <Link className="bg-slate-400 p-5 rounded-lg" href={"/favorites"}>
            Favorites
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
